require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe LeaveAvailsController do

  # This should return the minimal set of attributes required to create a valid
  # LeaveAvail. As you add validations to LeaveAvail, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all leave_avails as @leave_avails" do
      leave_avail = LeaveAvail.create! valid_attributes
      get :index
      assigns(:leave_avails).should eq([leave_avail])
    end
  end

  describe "GET show" do
    it "assigns the requested leave_avail as @leave_avail" do
      leave_avail = LeaveAvail.create! valid_attributes
      get :show, :id => leave_avail.id.to_s
      assigns(:leave_avail).should eq(leave_avail)
    end
  end

  describe "GET new" do
    it "assigns a new leave_avail as @leave_avail" do
      get :new
      assigns(:leave_avail).should be_a_new(LeaveAvail)
    end
  end

  describe "GET edit" do
    it "assigns the requested leave_avail as @leave_avail" do
      leave_avail = LeaveAvail.create! valid_attributes
      get :edit, :id => leave_avail.id.to_s
      assigns(:leave_avail).should eq(leave_avail)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new LeaveAvail" do
        expect {
          post :create, :leave_avail => valid_attributes
        }.to change(LeaveAvail, :count).by(1)
      end

      it "assigns a newly created leave_avail as @leave_avail" do
        post :create, :leave_avail => valid_attributes
        assigns(:leave_avail).should be_a(LeaveAvail)
        assigns(:leave_avail).should be_persisted
      end

      it "redirects to the created leave_avail" do
        post :create, :leave_avail => valid_attributes
        response.should redirect_to(LeaveAvail.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved leave_avail as @leave_avail" do
        # Trigger the behavior that occurs when invalid params are submitted
        LeaveAvail.any_instance.stub(:save).and_return(false)
        post :create, :leave_avail => {}
        assigns(:leave_avail).should be_a_new(LeaveAvail)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        LeaveAvail.any_instance.stub(:save).and_return(false)
        post :create, :leave_avail => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested leave_avail" do
        leave_avail = LeaveAvail.create! valid_attributes
        # Assuming there are no other leave_avails in the database, this
        # specifies that the LeaveAvail created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        LeaveAvail.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => leave_avail.id, :leave_avail => {'these' => 'params'}
      end

      it "assigns the requested leave_avail as @leave_avail" do
        leave_avail = LeaveAvail.create! valid_attributes
        put :update, :id => leave_avail.id, :leave_avail => valid_attributes
        assigns(:leave_avail).should eq(leave_avail)
      end

      it "redirects to the leave_avail" do
        leave_avail = LeaveAvail.create! valid_attributes
        put :update, :id => leave_avail.id, :leave_avail => valid_attributes
        response.should redirect_to(leave_avail)
      end
    end

    describe "with invalid params" do
      it "assigns the leave_avail as @leave_avail" do
        leave_avail = LeaveAvail.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        LeaveAvail.any_instance.stub(:save).and_return(false)
        put :update, :id => leave_avail.id.to_s, :leave_avail => {}
        assigns(:leave_avail).should eq(leave_avail)
      end

      it "re-renders the 'edit' template" do
        leave_avail = LeaveAvail.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        LeaveAvail.any_instance.stub(:save).and_return(false)
        put :update, :id => leave_avail.id.to_s, :leave_avail => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested leave_avail" do
      leave_avail = LeaveAvail.create! valid_attributes
      expect {
        delete :destroy, :id => leave_avail.id.to_s
      }.to change(LeaveAvail, :count).by(-1)
    end

    it "redirects to the leave_avails list" do
      leave_avail = LeaveAvail.create! valid_attributes
      delete :destroy, :id => leave_avail.id.to_s
      response.should redirect_to(leave_avails_url)
    end
  end

end
